// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kqlZnyxQwn-Ncrq0PICBeodMr-tvL-g',
    appId: '1:206280938500:web:261426c32b5df22809d151',
    messagingSenderId: '206280938500',
    projectId: 'authapp-61355',
    authDomain: 'authapp-61355.firebaseapp.com',
    storageBucket: 'authapp-61355.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1P9M_gM65-4ilIJZyM2PDPaVncpRZ0g',
    appId: '1:206280938500:android:d5b7c5ff1b903be909d151',
    messagingSenderId: '206280938500',
    projectId: 'authapp-61355',
    storageBucket: 'authapp-61355.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCRAT-PkZbqGT8Zap-xxzS5SmoJtG8Fps',
    appId: '1:206280938500:ios:4f071cca57a1b58309d151',
    messagingSenderId: '206280938500',
    projectId: 'authapp-61355',
    storageBucket: 'authapp-61355.appspot.com',
    iosClientId: '206280938500-458m5d0hni54ugg8dhbfve9qmmuup5qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCRAT-PkZbqGT8Zap-xxzS5SmoJtG8Fps',
    appId: '1:206280938500:ios:4f071cca57a1b58309d151',
    messagingSenderId: '206280938500',
    projectId: 'authapp-61355',
    storageBucket: 'authapp-61355.appspot.com',
    iosClientId: '206280938500-458m5d0hni54ugg8dhbfve9qmmuup5qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneapp',
  );
}
